# Generated by Django 5.0.6 on 2024-07-14 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('bio', models.TextField()),
                ('course', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('national_id', models.PositiveBigIntegerField(unique=True)),
                ('account_number', models.PositiveIntegerField(unique=True)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('department', models.CharField(max_length=25)),
            ],
        ),
    ]
