# Generated by Django 5.0.6 on 2024-07-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='years_of_experience',
        ),
    ]
