# Generated by Django 5.0.6 on 2024-07-14 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=100)),
                ('fee', models.PositiveSmallIntegerField(default=0)),
                ('course_code', models.PositiveSmallIntegerField(unique=True)),
                ('content', models.TextField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('duration_in_hours', models.DurationField(default=1)),
                ('department', models.CharField(max_length=25)),
                ('department_code', models.PositiveSmallIntegerField(unique=True)),
                ('number_of_students', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
