# Generated by Django 5.0.6 on 2024-07-14 18:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField(default='0000-00-00')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('profile', models.ImageField(upload_to='')),
                ('student_gender', models.CharField(max_length=20)),
                ('bio', models.TextField(default='I am a student')),
                ('national_id', models.IntegerField(default=0)),
                ('joining_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('parent', models.CharField(max_length=50)),
                ('next_of_kin', models.CharField(max_length=50)),
                ('parent_number', models.CharField(max_length=15)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.classes')),
            ],
        ),
    ]
